### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bknill** [sybond/MiSphere-hack#2]
Sorry for my ignorance. How do I use these? Just copy the files onto the SD Card?

Thanks

**Comment by sybond** [comment]
It should be something like:

1. [Enable telnet daemon](https://github.com/sybond/MiSphere-hack#shell-access)
2. Login using `root` (no password needed)
3. Edit `wifi.conf`, save it, restart the device

Note: for location of wifi.conf please see [this file](https://github.com/sybond/MiSphere-hack/blob/master/root_structure.txt). I think you can try with `/pref` version of `wifi.conf`.

**Comment by bknill** [comment]
Cool man thanks.
