### ISSUE TITLE
unpacking fw.  how did you?

### ISSUE THREAD

**Issue by clort81** [sybond/MiSphere-hack#3]
goprawn had some discussion about the ambarella a12 fw and unpacking, but the site is blocked by cloudflare for me.

how do you unpack the firmware, e.g.  a12_fw_for_upgrade_1.3.107.115.5.18497.devfw 

ty for the info

**Comment by sybond** [comment]
Hi, 

I'm not trying to unpack the firmware, just tinkering how the systems work. That time my objective just to able to connect my Bluetooth app to the HW. That's why I start to checking the OS/Ambarella.

**Comment by clort81** [comment]
Sorry to bug you but how do i get to shell on the misphere?  
I see ambsh is a thing, but not howto get shell on the misphere.
Cloudflare is blocking goprawn so i can't see discussions there.

**Comment by sybond** [comment]
> Sorry to bug you but how do i get to shell on the misphere?

See here https://github.com/sybond/MiSphere-hack#shell-access

Basically using the autoexec.ash script to run telnet daemon. After that you can telnet to the device.

**Comment by clort81** [comment]
Thanks for your response!  The linked page states:

"Enabled by adding autoexec.ash, following entries:
sleep 5
t ipc rpc clnt exec2 '/usr/sbin/telnetd > /dev/null'
Basically just running the Telnet Daemon during startup. User: root, without password."

Does this need uart console?  Could I get shell over usb or wifi?

**Comment by sybond** [comment]
If you meant the file, it get loaded in the SD Card. For telnet it self, as I remembered I'm using the device local WiFi network to do telnet.

**Comment by clort81** [comment]
aha, so i put the autoexec.ash on the sdcard?  and that gets run?

IT WORKS! :D
